### PR TITLE
Use irrelevance quantification .{s} for sizes

### PR DESCRIPTION
**Pull request by Saizan**
The main point of .. at the moment is to be able to use irrelevant arguments in types as if they weren't so you have more equalities.
You might want to consider this. I haven't type-checked the code though!

### CODE REVIEW

**Comment by jonsterling** [comment]
@Saizan thanks! Is there something I can read that goes into detail on what `..` actually does in comparison to `.`?

**Comment by freebroccolo** [comment]
@Saizan interesting, thanks for the comment! I'll give it a try and see how it works.

**Comment by freebroccolo** [comment]
@Saizan so I tried to type check the `Vec` example but the following does not work:

```agda
data Vec ..{s} (A : Set) : Nat → Set where
  []
    : Vec {s} A ze
  _∷_
    : ∀ .{s′ : Size.< s} {n}
    → A
    → Vec {s′} A n
    → Vec {s} A (su n)
```

It complains:

```
Variable s′ is declared irrelevant, so it cannot be used here when checking that the expression s′ has type Size
```

If I change it to the following:

```agda
data Vec .{s} (A : Set) : Nat → Set where
  []
    : Vec {s} A ze
  _∷_
    : ∀ .{s′ : Size.< s} {n}
    → A
    → Vec {s′} A n
    → Vec {s} A (su n)
```

(using a single `.` for the parameter) it still complains:

```
Variable s is declared irrelevant, so it cannot be used here when checking that the expression s has type Size
```

In the latter case it does not like the fact that `s` is being used with `Size.<`. So in fact the only combination that seems to work is how I have it now with `..` in both places. Unfortunately, that doesn't  appear to have any real effect on on equalities when trying to prove something with equational reasoning where the sizes differ.

Is there something else needed to make this work?

**Comment by freebroccolo** [comment]
Actually, maybe it does work if I also use the ``--experimental-irrelevance`` flag. Trying some stuff now…

**Comment by Saizan** [comment]
Yes, sorry, forgot about that flag

**Comment by freebroccolo** [comment]
After some more experimenting I was able to get it to work for the examples we had originally been looking at. Thanks for the tip.

**Pull request closed without merging**
