### PR TITLE
Add Travis CI config.

### PR DESCRIPTION
**Pull request by scott-fleischman**
It builds on my fork: https://travis-ci.org/scott-fleischman/agda-prelude/builds/158357697

### CODE REVIEW

**Comment by freebroccolo** [comment]
This looks really nice, thanks!

Would you mind disabling email notifications at the top of travis config file and adding a build badge to the README? You can check the config in the yggdrasil repository for reference.

**Comment by scott-fleischman** [comment]
Done. Also, feel free to push changes to my fork if you want to make further changes before merging, now that GitHub supports the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) option in pull requests.

**Comment by scott-fleischman** [comment]
Or of course just let me know and I'll make any further changes. I was mainly pointing out that you could push the fork if you like.

**Comment by freebroccolo** [comment]
That option looks interesting. Didn't know about that. By the way, I added you as a collaborator so feel free to make changes if you see something that could be improved.

**Pull request merged**
